In [1]:
#Q1:- Create a numpy array 'arr' of integer form 0 to 5 and print its data type.?

import numpy as np
arr=np.array([0,1,2,3,4,5])
print(arr)
type(arr)

[0 1 2 3 4 5]


numpy.ndarray

In [6]:
#Q2:- Given a Numpy array 'arr' , check if its data type is float64.
# arr=np.array([1.5,2.6,3.7])
import numpy as np
arr=np.array([1.5,2.6,3.7])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
float64


In [14]:
#Q3:- Create anumpy array 'arr' with a data type  of complex128 containing three complex numbers.
import numpy as np
arr=np.array([1 + 2j, 2 + 3j, 4 + 5j], dtype=np.complex128)
arr


array([1.+2.j, 2.+3.j, 4.+5.j])

In [17]:
#Q4:- 4. Convert an existing Numpy array 'arr' of integers to foat32 data type.
import numpy as np
arr=np.array([1,2,3,4,45])
arr_float=arr.astype(np.float32)
print(arr_float.dtype)


float32


In [2]:
#Q5:- Given a Numpy array 'arr' with float64 data type, conrt it to float32 to reduce decimal precision.
import numpy as np
arr=np.array([1,2,3,4,45])
arr_float32=arr.astype(np.float32)
print(arr_float32.dtype)
print(arr_float32)
print()
arr_float64=arr.astype(np.float64)
print(arr_float64.dtype)
print(arr_float64)

float32
[ 1.  2.  3.  4. 45.]

float64
[ 1.  2.  3.  4. 45.]


In [15]:
#Q6:- write a function array_dimension that takes a numpy array as input and return its dimensionality.
import numpy as np

def array_dimension(arr):
    return arr.ndim

# Example usage:
arr = np.array([1, 2, 3, 4, 5])
print(array_dimension(arr))  # Output: 1

arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))  # Output: 2

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_dimension(arr))  # Output: 3

1
2
3


In [5]:
#Q7: Create a function array_dimension that takes a numpy array as input and return the item size ,shape and data type .
import numpy as np
def array_dimension(arr):
    return arr.shape,arr.size,arr.dtype

# Example usage:
arr = np.array([1, 2, 3, 4, 5])
print(array_dimension(arr)) 

arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))  

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_dimension(arr))  

((5,), 5, dtype('int32'))
((2, 2), 4, dtype('int32'))
((2, 2, 2), 8, dtype('int32'))


In [1]:
#Q8:- Design a function item_size_info that takes a numpy array as input and return the item size and the total size in bytes.
import numpy as np
def item_size_info(arr):
    #get the item size of array
    item_size=arr.itemsize
    #get the total size of array
    total_size=arr.size*item_size
    return item_size,total_size

arr = np.array([1, 2, 3, 4, 5])
print(item_size_info(arr))

(4, 20)


In [2]:
#Q9:- create a function array_strides that takes array as input and returns the strides of the array.
"""Strides represent the number of bytes that need to be skipped in memory to move to the next element along each dimension of the array."""
import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_strides(arr)

(12, 4)

In [3]:
#Q10:- design a function shape_stide_relationship that takes a numpy array as input and returns the shape and strides of the array.
import numpy as np
def shape_stide_relationship(arr):
    return arr.shape,arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape_stide_relationship(arr)

((3, 3), (12, 4))

In [7]:
#Q11:- create a function 'create_zeros_array' the takes an integer 'n' as input and returns a numpy array of zeros with'n' elements.
import numpy as np 
def create_zeros_array(n):
    return np.zeros(n)

n=int(input("Enter the number for array:"))
create_zeros_array(n)

array([0., 0., 0., 0., 0.])

In [29]:
#Q12:- Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as input and generate as 2d numpy array filled with ones of size 'row x cols'.
import numpy as np 
def create_ones_matrix(rows,cols):
    return np.ones((rows,cols))

rows=int(input("Enter the number of rows: "))
cols=int(input("Enter the number of cols: "))
print(create_ones_matrix(rows,cols))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [30]:
#Q13:- Write a function 'generate_range_array' that takes three integers start , stop,and step as arguments and creates a numpy array with a range starting from 'start', ending at stop(exclusive), and with the specified 'step'.
import numpy as np
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)

generate_range_array(2,15,2)


array([ 2,  4,  6,  8, 10, 12, 14])

In [52]:
#Q14:- Design a function 'create-indentity-matrix' that takes an integer n as input and generates a square identity matrix of the size nxn using  numpy.eye  ?
import numpy as np
def create_indentity_matrix(n):
    return np.eye(n,n)

n=int(input("Enter the square matrix size: "))
print(n)
create_indentity_matrix(n)

5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1]:
#Q15:- desigen a function 'generate_linear-spaces' that takes two floates start ,stop and an integer num as arguments and generates a numpy array with num equally spaced  start and stop (inclusive).
import numpy as np
def generate_linear_spaces(start,stop,step):
    return np.linspace(start,stop,step)

generate_linear_spaces(2.0,5.0,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [2]:
#Q16:- Write a function that taked a python list and converts it into a numpy array.
import numpy as np
def Numpy_array(list):
    return np.array(list)

list=[1,2,3,4,5,5]
Numpy_array(list)

array([1, 2, 3, 4, 5, 5])

In [8]:
#Q17:- create a numpy array and demonstrate the use of  'numpy.view' to create array object with the same data.
import numpy as np
arr=np.array([2,3,4,4,5],dtype=np.int32)
print(arr)

View=arr.view(np.float32)
print(View.dtype)
print(View)

[2 3 4 4 5]
float32
[3.e-45 4.e-45 6.e-45 6.e-45 7.e-45]


In [13]:
#Q18:-Write a function that takes two numpy arrays and concatenates them along a specified axis.
import numpy as np
def concat_arrays(arr1,arr2,axis):
    return np.concatenate((arr1,arr2),axis)

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[6,7]])
print(concat_arrays(arr1,arr2,axis=1))
print(concat_arrays(arr1,arr2,axis=0))

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [24]:
import numpy as np

# Create two numpy arrays with different shapes
arr1 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])  # 2D array with shape (2, 4)
arr2 = np.array([[3, 4], [5, 6]])  # 2D array with shape (2, 2)

# Now we can concatenate them horizontally
arr_concat = np.concatenate((arr1, arr2), axis=1)  # Concatenate horizontally (axis=1)

print(arr_concat)

[[1 2 3 4 3 4]
 [3 4 5 6 5 6]]


In [25]:
#Q20:-Write a function that vertically stacks multiple numpy arrays given as a list.
import numpy as np
def Vertically_stack_array(arrays):
    return np.vstack(arrays)

arr1=np.array([[2,3],[3,4]])
arr2=np.array([[2,4],[8,4]])
arr3=np.array([[5,3],[9,4]])

arrays=[arr1,arr2,arr3]

Vertically_stack_array(arrays)

array([[2, 3],
       [3, 4],
       [2, 4],
       [8, 4],
       [5, 3],
       [9, 4]])

In [1]:
#Q21:- write a python function using numpy to create an array of integers within a specified range(inclusive) with a given step size.
import numpy as np
def numpy_func(start,end,step):
    return np.arange(start,end+step,step)

numpy_func(2,10,3)

array([ 2,  5,  8, 11])

In [2]:
#Q22:- write a pyhton function using numpy to generate an array of 10 equally spaced between 0 and 1 (inclusive).
import numpy as np
def py_func(start,end,no_element):
    return np.linspace(start,end,no_element)

py_func(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [2]:
#Q23:- write a pyhton function using numpy to create an array of 5 logarithmically spaced values between 1 and 1000(inclusive).
import numpy as np
def logrithmic_space_value(start,end,num_element):
    return np.logspace(start,end,num_element,base=2)  

logrithmic_space_value(1,1000,5)

array([2.00000000e+000, 3.04278602e+075, 4.62927339e+150, 7.04294419e+225,
       1.07150861e+301])

In [16]:
#Q24:- Create a pandas dataframe using a numpy array that contains 5 rows and 3 columns , where the Values are random integers between 1 and 100.
import pandas as pd
import numpy as np
def pandas_dataframe(rows,cols,minvalue,maxvalue):
    arr=np.random.randint(minvalue,maxvalue+1,size=(rows,cols))
    df=pd.DataFrame(arr,columns=[f'column{i+1}' for i in range(cols)])
    return df

pandas_dataframe(5,3,1,100)

column1  column2  column3
0       27       87       34
1       84       92       78
2       56        8       62
3       46       33       85
4       41       87       53

In [2]:
#Q25:- Write a function that takes a pandas Dataframe and replace all negative Value in a specific column with zeros. Use numpy operations within the pandas Dataframes.
import pandas as pd
import numpy as np

def pandas_dataframe(rows,cols,minvalue,maxvalue):
    arr=np.random.randint(minvalue,maxvalue+1,size=(rows,cols))
    df=pd.DataFrame(arr,columns=[f'column{i+1}' for i in range(cols)])
    return df

def positive_int_dataframe(dt,column_name):
    dt[column_name]=np.where(dt[column_name]<0,0,dt[column_name])
    return dt

#example use
dt=pandas_dataframe(5,3,-100,100)
print("original dataframe: ")
print(dt)

#replacing negative Value of column2 with 0
column_name="column2"
dt=positive_int_dataframe(dt,column_name)
print(f"\nDataFrame after replacing negative values in {column_name} with zeros:")
print(dt)


original dataframe: 
   column1  column2  column3
0      -50      -67       14
1      -74       10       40
2       56      -63       11
3       20      -44      -36
4      -56       48       -7

DataFrame after replacing negative values in column2 with zeros:
   column1  column2  column3
0      -50        0       14
1      -74       10       40
2       56        0       11
3       20        0      -36
4      -56       48       -7


In [3]:
#Q26:-Acces the 3rd element from the giVen Numpy array.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Third element:",arr[2])

Third element: 30


In [6]:
#Q27:-Retrieve the element at index (1, 2) from the 2D NumPy array. 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])   

print("retrive element at index (1,2) is : ",arr_2d[1,2])

retrive element at index (1,2) is :  6


In [8]:
#Q28:- Using boolean indexing, extract elements greater than 5 from the given NumPy array.  
arr = np.array([3, 8, 2, 10, 5, 7])

print("original array:",arr)

arr=arr[arr>5]
print("arr which element is greater than 5:",arr)

original array: [ 3  8  2 10  5  7]
arr which element is greater than 5: [ 8 10  7]


In [12]:
#Q29:- Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 

#solution
sliced_arr=arr[2:6]
print("Sliced array:",sliced_arr)



Sliced array: [3 4 5 6]


In [16]:
#Q30:- Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],                    
                   [4, 5, 6], 
                   [7, 8, 9]])

#solution 
import numpy as np
sub_array=arr_2d[0:2,1:3]# Rows 0 to 1 (inclusive), Columns 1 to 2 (inclusive)
print(sub_array)


[[2 3]
 [5 6]]


In [1]:
#Q31:-.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array. 
import numpy as np
def exract_function(arr,indices):
    return arr[indices[:,0],indices[:,1]]

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
indices=np.array([[0,1],[1,2],[2,0]])

exract_function(arr,indices)

array([2, 6, 7])

In [2]:
#Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_elements(arr,threshold):
    boolean_mask=arr>threshold

    return arr[boolean_mask]


#example use 
array1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])
threshold = 10
filter_elements(array1,threshold)

array([11, 16, 18, 22, 26, 31, 33, 47, 51, 52])

In [2]:
#Q33:- Develop a numpy function that extracts specific elements from a 3D array using indices provided in three sepreate arrays for each dimension
import numpy as np

def extract_elements_3d(array, idx_x, idx_y, idx_z):
    # Convert indices to a tuple for advanced indexing
    return array[idx_x, idx_y, idx_z]

# Example usage
arr = np.arange(3 * 3 * 3).reshape((3, 3, 3))  # A 3x3x3 array

# Indices for each dimension
idx_x = np.array([0, 1, 2])  # Indices along the first dimension (x-axis)
idx_y = np.array([1, 0, 2])  # Indices along the second dimension (y-axis)
idx_z = np.array([2, 1, 0])  # Indices along the third dimension (z-axis)

# Extract the elements
extracted_elements = extract_elements_3d(arr, idx_x, idx_y, idx_z)
print("Extracted elements:", extracted_elements)


Extracted elements: [ 5 10 24]


In [5]:
#Q34: Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def elements_with_conditions(array, cond1, cond2):
    # Apply both conditions using boolean indexing
    return array[(cond1) & (cond2)]

# Example usage
arr = np.array([10, 15, 20, 25, 30, 35])

# Conditions: elements greater than 15 and less than 30
cond1 = arr > 15
cond2 = arr < 30

# Get elements satisfying both conditions
result = elements_with_conditions(arr, cond1, cond2)
print("Elements satisfying both conditions:", result)



Elements satisfying both conditions: [20 25]


In [6]:
#Q35- Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements_2d(array, row_indices, col_indices):
    # Use advanced indexing to extract elements
    return array[row_indices, col_indices]

# Example usage
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

# Indices for rows and columns
row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([2, 1, 0])  # Column indices

# Extract elements from the 2D array
extracted_elements = extract_elements_2d(arr, row_indices, col_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [30 50 70]


In [7]:
#Q36:- Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

def add_scalar(arr, scalar):
    # Add the scalar to the array using broadcasting
    return arr + scalar

# Example usage
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Add scalar value of 5 to each element
result = add_scalar(arr, 5)
print("Resulting array:\n", result)




Resulting array:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [8]:
#Q37:- Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np

def multiply_rows(arr1, arr2):
    # Transpose arr1 to shape (3, 1) and use broadcasting for multiplication
    return arr2 * arr1.T

# Example usage
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[ 4,  5,  6,  7], 
                 [ 8,  9, 10, 11], 
                 [12, 13, 14, 15]])  # Shape (3, 4)

result = multiply_rows(arr1, arr2)
print("Resulting array:\n", result)


Resulting array:
 [[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [9]:
#Q38:- Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

def add_to_rows(arr1, arr2):
    return (arr2.T + arr1).T

# Example usage
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90], 
                 [100, 110, 120]])  # Shape (4, 3)

result = add_to_rows(arr1, arr2)
print("Resulting array:\n", result)


Resulting array:
 [[ 11  21  31]
 [ 42  52  62]
 [ 73  83  93]
 [104 114 124]]


In [10]:
#Q39:-Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

def add_arrays(arr1, arr2):
    return arr1 + arr2

# Example usage
arr1 = np.array([[1],
                  [2],
                  [3]])  # Shape (3, 1)

arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

result = add_arrays(arr1, arr2)
print("Resulting array:\n", result)


Resulting array:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [11]:
#40:- Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. H andle the shape incompatibility

import numpy as np

def matrix_multiplication(arr1, arr2):
    # Transpose arr1 to make it compatible
    arr1_T = arr1.T
    return np.dot(arr1_T, arr2)

# Example usage
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[7, 8],
                 [9, 10]])  # Shape (2, 2)

result = matrix_multiplication(arr1, arr2)
print("Resulting array:\n", result)


Resulting array:
 [[43 48]
 [59 66]
 [75 84]]


In [12]:
#Q41-: Calculate column-wise mean for the given array: 
arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)          ##axis=0: This specifies that the mean should be computed along the vertical axis (i.e., for each column).
print("Column-wise mean:", column_mean)


Column-wise mean: [2.5 3.5 4.5]


In [13]:
#Q42:- Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)              ##axis=1<< along the horizontal axis 
print("Maximum value in each row:", row_max)


Maximum value in each row: [3 6]


In [14]:
#Q43:-  For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
column_max_indices = np.argmax(arr, axis=0)
print("Indices of maximum values in each column:", column_max_indices)


Indices of maximum values in each column: [1 1 1]


In [15]:
#Q44:- For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

import numpy as np

def moving_sum(arr, window_size):
    rows, cols = arr.shape
    # Calculate the number of columns in the result
    result = np.zeros((rows, cols - window_size + 1), dtype=int)
    
    for i in range(rows):
        for j in range(cols - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

window_size = 2  # Define the window size

moving_sum_result = moving_sum(arr, window_size)
print("Moving sum along rows:\n", moving_sum_result)


Moving sum along rows:
 [[ 3  5]
 [ 9 11]]


In [21]:
#Q45:- In the given array, check  if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements are even
all_even = np.all(arr % 2 == 0,axis=0)

print("All elements in each column are even:", all_even)


All elements in each column are even: [False False False]


In [22]:
#Question 46: Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Desired dimensions
m, n = 2, 3

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:\n", reshaped_matrix)


Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [24]:
#Question 47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]]) 

import numpy as np

def flatten_matrix(matrix):
    # Flatten the matrix to a 1D array
    flattened_array = matrix.flatten()   #we can use  ravel
    return flattened_array

# Example usage
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)
print("Flattened array:\n", flattened_array)


Flattened array:
 [1 2 3 4 5 6]


In [25]:
#Question 48. Write a function that concatenates two given arrays along a specified axis. 
array1 = np.array([[1, 2], [3, 4]]) 
array2 = np.array([[5, 6], [7, 8]])

import numpy as np

def concatenate_arrays(array1, array2, axis):
    # Concatenate the arrays along the specified axis
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Example usage
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis0)

# Concatenate along axis 1 (columns)
concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [28]:
#Question 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

import numpy as np

def split_array(array, num_splits, axis):
    # Split the array into `num_splits` sub-arrays along the specified axis
    sub_arrays = np.array_split(array, num_splits, axis=axis)
    return sub_arrays

# Example usage
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Split into 3 sub-arrays along axis 0 (rows)
split_axis0 = split_array(original_array, num_splits=3, axis=0)
print(split_axis0 )
print("Split along axis 0:")
for sub_array in split_axis0:
    print(sub_array)

print()

# Split into 2 sub-arrays along axis 1 (columns)
split_axis1 = split_array(original_array, num_splits=2, axis=1)
print(split_axis1)
print("\nSplit along axis 1:")
for sub_array in split_axis1:
    print(sub_array)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

[array([[1, 2],
       [4, 5],
       [7, 8]]), array([[3],
       [6],
       [9]])]

Split along axis 1:
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [29]:
#Question 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5]) 
indices_to_insert = [2, 4] 
values_to_insert = [10, 11] 
indices_to_delete = [1, 3]

import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements into the array
    array_with_insertions = np.insert(original_array, indices_to_insert, values_to_insert)
    
    # Delete elements from the array
    array_after_deletion = np.delete(array_with_insertions, indices_to_delete)
    
    return array_after_deletion

# Example usage
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array after insertion and deletion:\n", result_array)


Resulting array after insertion and deletion:
 [ 1 10  4 11  5]


In [1]:
#Question 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`. 
import numpy as np

# Create arr1 with random integers (e.g., 2x3 matrix with values between 0 and 9)
arr1 = np.random.randint(0, 10, size=(2, 3))

# Create arr2 with integers from 1 to 10 (e.g., 2x3 matrix)
arr2 = np.arange(1, 7).reshape(2, 3)

# Perform element-wise addition
result = arr1 + arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of element-wise addition:\n", result)


arr1:
 [[2 6 5]
 [2 5 7]]
arr2:
 [[1 2 3]
 [4 5 6]]
Result of element-wise addition:
 [[ 3  8  8]
 [ 6 10 13]]


In [2]:
#Question 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise. 

import numpy as np

# Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of element-wise subtraction:\n", result)


arr1:
 [10  9  8  7  6  5  4  3  2  1]
arr2:
 [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction:
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [5]:
#Question 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.  
import numpy as np

# Create arr1 with random integers (e.g., 2x5 matrix with values between 1 and 10)
arr1 = np.random.randint(1, 10, size=(2, 5))

# Create arr2 with integers from 1 to 5 (e.g., 2x5 matrix)
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of element-wise multiplication:\n", result)


arr1:
 [[7 5 5 2 9]
 [4 5 4 5 1]]
arr2:
 [1 2 3 4 5]
Result of element-wise multiplication:
 [[ 7 10 15  8 45]
 [ 4 10 12 20  5]]


In [6]:
#Question 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.  
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of element-wise division:\n", result)


arr1:
 [ 2  4  6  8 10]
arr2:
 [1 2 3 4 5]
Result of element-wise division:
 [2. 2. 2. 2. 2.]


In [7]:
#Question 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise. 
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create arr2 with the reversed sequence of arr1
arr2 = np.flip(arr1)

# Perform element-wise exponentiation
result = arr1 ** arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of element-wise exponentiation:\n", result)


arr1:
 [1 2 3 4 5]
arr2:
 [5 4 3 2 1]
Result of element-wise exponentiation:
 [ 1 16 27 16  5]


In [9]:
#Question 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

import numpy as np

def count_substring_occurrences(arr, substring):
    # Use np.char.find to check if the substring is in each element of the array
    occurrences = np.char.find(arr, substring) != -1
    
    # Sum the boolean array to get the count of occurrences
    count = np.sum(occurrences)
    
    return count

# Example usage
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}':", result)


Occurrences of 'lello': 0


In [2]:
#Question 57. Write a function that extracts uppercase characters from a NumPy array of strings. 
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

import numpy as np
def extract_uppercase_characters(arr):
    #create a list to store uppercase characters
    uppercase_chars=[]

    #iterate over each string n the arraay
    for s  in arr:
        #Extract uppercase characters from the string
        uppercase_chars.extend([char for char in s if char.isupper()])

    #Convert the list to a numpy array and return
    return np.array(uppercase_chars)    

## Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase_characters(arr)

print("Uppercase characters:", result)

Uppercase characters: ['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [3]:
#Question 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace old_substring with new_substring
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)

print("Array after replacement:", result)


Array after replacement: ['orange' 'banana' 'grape' 'pineorange']


In [4]:
#Question 59. Write a function that concatenates strings in a NumPy array element-wise
arr1 = np.array(['Hello', 'World']) 
arr2 = np.array(['Open', 'AI'])

import numpy as np

def concatenate_strings(arr1, arr2):
    # Use np.char.add to concatenate strings element-wise
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)

print("Concatenated array:", result)


Concatenated array: ['HelloOpen' 'WorldAI']


In [5]:
#Question 60. Write a function that finds the length of the longest string in a NumPy array. 
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])   
import numpy as np

def find_longest_string_length(arr):
    # Use np.vectorize to apply the len function to each string in the array
    string_lengths = np.vectorize(len)(arr)
    
    # Find and return the maximum length
    return np.max(string_lengths)

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = find_longest_string_length(arr)

print("Length of the longest string:", longest_length)


Length of the longest string: 9


In [6]:
#Question 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
import numpy as np

# Step 1: Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Step 2: Compute statistical metrics
mean_value = np.mean(dataset)
median_value = np.median(dataset)
variance_value = np.var(dataset)
std_deviation_value = np.std(dataset)

# Output the results
print("Dataset:", dataset)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)


Dataset: [101 496 796 549 562 759 353 703  86 558  41 619 697 387 839 930 858 540
 507 583 583 935 814 697 837 267 672 750 669 748  70 271 346 886 564 283
 296  49 765 170 514 803 296 751 101 593 659 817 682 378 551  29 932 636
 544 699 365 579 500 880 717 853 548   1 886 890 140 911 523 343  80 613
 172 642 893 759 265 113 105 281 139 557 279 245 404 388 608 861 297 925
 365 413 900 583 682 743 369 565 250 378]
Mean: 526.31
Median: 560.0
Variance: 69604.45390000001
Standard Deviation: 263.8265602626089


In [7]:
#Question 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset. 
import numpy as np

# Step 1: Generate an array of 50 random numbers between 1 and 100
random_numbers = np.random.uniform(1, 100, size=50)

# Step 2: Compute the 25th and 75th percentiles
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

# Output the results
print("Random Numbers:\n", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Random Numbers:
 [90.75842224 91.58771691 40.08328756 17.24121947 65.64248881 25.54894146
 42.44998958 56.27450815 74.57140959 12.55341097 66.51305767 77.67350412
  4.54168542 20.46696585 52.14458356 70.80579994 31.90931348 61.10228835
 78.84389113  3.42164517 70.97070304 45.62046935 68.70572139 93.68752821
 97.54426674 79.4773675   3.54816637 33.37813781 10.92069756 18.84903817
 43.22161908 24.79246484  1.29328003 45.92278952 51.9695262  76.21378001
 53.79386746 19.96893244 78.07890742 69.07323102 93.06853702 48.42203305
 39.88247471 15.62580796 90.2119126  25.20915875 81.22579783 67.29551744
 82.85803928 53.85542454]
25th Percentile: 25.29410442461971
75th Percentile: 75.80318740705685


In [9]:
#Question 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function. 
import numpy as np

# Step 1: Create two arrays representing two sets of variables
array1 = np.random.randint(1, 100, size=50)
array2 = np.random.randint(1, 100, size=50)

# Step 2: Compute the correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)

# The correlation coefficient is the element [0, 1] or [1, 0] in the matrix
correlation_coefficient = correlation_matrix[0, 1]

# Output the results
print("Array 1:", array1)
print("Array 2:", array2)
print(correlation_matrix)
print("Correlation Coefficient:", correlation_coefficient)


Array 1: [ 5 14 50 46 52 72 63 64 48 89 62 64 89 47 75 80 84 29 59 31  6 79 91 16
 34 42 88 45  2 71  6 31 38 82 76  2 22 88 92 82 43 28 21 96 52 51 14 53
 74 76]
Array 2: [72 64 94 29  6 66 95 35 64  1 86 93  1 35 52 74 51 88 78 15 15  4 93 12
 49 97 48 15 95 57 91 80 26 13 15 38 11 67 27 62 50 54  9 83  1 62 18 84
 51 63]
[[1.         0.00223717]
 [0.00223717 1.        ]]
Correlation Coefficient: 0.002237167574506114


In [10]:
#Question 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
#answer:Matrix multiplication can be performed using NumPy’s dot function or the @ operator. In matrix multiplication, the number of columns in the first matrix must match the number of rows in the second matrix

import numpy as np

# Step 1: Create two matrices
matrix1 = np.random.randint(1, 10, size=(3, 2))  # A 3x2 matrix
matrix2 = np.random.randint(1, 10, size=(2, 3))  # A 2x3 matrix

# Step 2: Perform matrix multiplication
result = np.dot(matrix1, matrix2)  # Or use matrix1 @ matrix2

# Output the matrices and the result
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of matrix multiplication:\n", result)


Matrix 1:
 [[8 3]
 [6 8]
 [3 4]]
Matrix 2:
 [[3 8 7]
 [5 5 2]]
Result of matrix multiplication:
 [[39 79 62]
 [58 88 58]
 [29 44 29]]


In [11]:
#Question 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
import numpy as np

# Step 1: Generate an array of 50 random integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Step 2: Calculate the required percentiles
percentile_10 = np.percentile(arr, 10)   # 10th percentile
percentile_50 = np.percentile(arr, 50)   # 50th percentile (median)
percentile_90 = np.percentile(arr, 90)   # 90th percentile

# Step 3: Calculate the first and third quartiles
first_quartile = np.percentile(arr, 25)  # Q1
third_quartile = np.percentile(arr, 75)  # Q3

# Output the results
print("Array:", arr)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", first_quartile)
print("Third Quartile (Q3):", third_quartile)


Array: [ 162  700  599  381  276  279  240  290  542  851  914  605  861 1000
  338  333  807  511  508  318  665  257  726  538  880  626  513  268
  875  236  904  553  935   99  176   44  672  169  304  438  289  368
   49  451  983  697  737  955  790  355]
10th Percentile: 175.3
50th Percentile (Median): 512.0
90th Percentile: 905.0
First Quartile (Q1): 289.25
Third Quartile (Q3): 734.25


In [12]:
#Question 66. Create a NumPy array of integers and find the index of a specific element.

import numpy as np

# Step 1: Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Step 2: Find the index of a specific element (e.g., 50)
element_to_find = 50
index = np.where(arr == element_to_find)

# Output the results
print("Array:", arr)
print(f"Index of {element_to_find}:", index[0])


Array: [10 20 30 40 50 60 70 80 90]
Index of 50: [4]


In [13]:
#Question 67. Generate a random NumPy array and sort it in ascending order. 
# 
# import numpy as np

# Step 1: Generate a random NumPy array
array_size = 10  # I can change the size as needed
random_array = np.random.randint(1, 100, size=array_size)  # Array of random integers between 1 and 100

# Step 2: Sort the array in ascending order
sorted_array = np.sort(random_array)  # Returns a new sorted array
# Alternatively, I can sort in place with: random_array.sort()

# Output the results
print("Original Array:", random_array)
print("Sorted Array:", sorted_array)
 

Original Array: [40 51 93 99 90 74 74 83 69 98]
Sorted Array: [40 51 69 74 74 83 90 93 98 99]


In [14]:
#Question 68. Filter elements >20  in the given NumPy array. 
arr = np.array([12, 25, 6, 42, 8, 30])

import numpy as np

# Step 1: Create the NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Step 2: Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Output the results
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_arr)


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [15]:
#Question 69. Filter elements which are divisible by 3 from a given NumPy array. 
arr = np.array([1, 5, 8, 12, 15])

import numpy as np

# Step 1: Create the NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Step 2: Filter elements divisible by 3
divisible_by_3 = arr[arr % 3 == 0]

# Output the results
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", divisible_by_3)


Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [16]:
#Question 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

import numpy as np

# Step 1: Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Step 2: Filter elements ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Output the results
print("Original Array:", arr)
print("Filtered Array (20 ≤ elements ≤ 40):", filtered_arr)


Original Array: [10 20 30 40 50]
Filtered Array (20 ≤ elements ≤ 40): [20 30 40]


In [17]:
#Question 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

"""Byte order, also known as endianness, refers to the sequence in which bytes are ordered within a multi-byte data type when stored in memory. It is crucial for correctly interpreting binary data across different systems or architectures
Output '<': Indicates little-endian.
Output '>': Indicates big-endian.
Output '=': Indicates native byte order.
Output '': Indicates no byte order (e.g., for single-byte types)
"""


Byte Order: =


In [18]:
#Question 72. For the given NumPy array, perform byte swapping in place using `byteswap()`. 
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Step 1: Create the NumPy array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Output the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Step 2: Perform byte swapping in place
arr.byteswap(inplace=True)

# Output the array after byte swapping and its byte order
print("Array After Byte Swapping:", arr)
print("Byte Order After Swapping:", arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array After Byte Swapping: [16777216 33554432 50331648]
Byte Order After Swapping: =


In [19]:
#Question 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Step 1: Create the NumPy array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Output the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Step 2: Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Output the new array with swapped byte order
print("Array With Swapped Byte Order:", swapped_arr)
print("Byte Order of Swapped Array:", swapped_arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array With Swapped Byte Order: [16777216 33554432 50331648]
Byte Order of Swapped Array: >


In [20]:
#Question 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. 
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Step 1: Create the NumPy array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Output the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Determine the desired byte order based on system endianness
# Let's assume we want to convert to big-endian ('>')
desired_byte_order = '>' if arr.dtype.byteorder != '>' else '='

# Swap byte order conditionally
swapped_arr = arr.newbyteorder(desired_byte_order)

# Output the new array with swapped byte order
print("Array With Conditionally Swapped Byte Order:", swapped_arr)
print("Byte Order of Swapped Array:", swapped_arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array With Conditionally Swapped Byte Order: [16777216 33554432 50331648]
Byte Order of Swapped Array: >


In [21]:
#Question 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`. 
arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np

# Step 1: Create the NumPy array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Output the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Determine the system's native byte order
native_byte_order = '='  # Native byte order is represented as '='

# Check if byte swapping is necessary
if arr.dtype.byteorder != native_byte_order:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Original Array: [1 2 3]
Original Byte Order: =
Byte swapping is not necessary.


In [22]:
#Question 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`
import numpy as np

# Step 1: Create a NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)

# Step 2: Create a copy of arr1
copy_arr = arr1.copy()

# Step 3: Modify an element in copy_arr
copy_arr[0] = 100  # Modify the first element

# Step 4: Check if modifying copy_arr affects arr1
print("Original Array (arr1):", arr1)
print("Modified Copy Array (copy_arr):", copy_arr)


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [23]:
#Question 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
import numpy as np

# Step 1: Create a 2D NumPy array with random integers
matrix = np.random.randint(0, 10, size=(3, 3))

# Step 2: Extract a slice from the matrix
# Here we take a sub-array that includes all rows and columns 1 and 2
view_slice = matrix[:, 1:3]   #matrix[:, 1:3] selects all rows (indicated by the :) and columns from index 1 to 2 (the end index 3 is exclusive).

# Step 3: Modify an element in the view_slice
view_slice[0, 0] = 100  # Modify the first element of the slice

# Step 4: Check if modifying view_slice affects matrix
print("Original Matrix:\n", matrix)
print("Modified Slice:\n", view_slice)


Original Matrix:
 [[  6 100   0]
 [  5   9   4]
 [  3   7   8]]
Modified Slice:
 [[100   0]
 [  9   4]
 [  7   8]]


In [24]:
#Question 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`. 
import numpy as np

# Step 1: Create a NumPy array with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Step 2: Extract a slice from array_a
# For example, extract the first two rows and columns
view_b = array_a[:2, :2]

# Step 3: Broadcast addition of 5 to view_b
view_b += 5

# Step 4: Check if modifying view_b affects array_a
print("Original Array (array_a):\n", array_a)
print("Modified Slice (view_b):\n", view_b)


Original Array (array_a):
 [[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
Modified Slice (view_b):
 [[ 6  7]
 [ 9 10]]


In [25]:
#Questio 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`. 
import numpy as np

# Step 1: Create the original array
orig_array = np.arange(1, 9).reshape(2, 4)

# Step 2: Create a reshaped view of shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)

# Step 3: Modify an element in reshaped_view
reshaped_view[1, 1] = 99

# Step 4: Check if modifying reshaped_view affects orig_array
print("Original Array (orig_array):\n", orig_array)
print("Reshaped View (reshaped_view):\n", reshaped_view)


Original Array (orig_array):
 [[ 1  2  3 99]
 [ 5  6  7  8]]
Reshaped View (reshaped_view):
 [[ 1  2]
 [ 3 99]
 [ 5  6]
 [ 7  8]]


In [26]:
#Question 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`. 
import numpy as np

# Step 1: Create the original array with random integers
np.random.seed(0)  # For reproducibility
data = np.random.randint(1, 10, size=(3, 4))

# Step 2: Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Step 3: Modify an element in data_copy
data_copy[0] = 99

# Step 4: Verify if modifying data_copy affects data
print("Original Array (data):\n", data)
print("Modified Copy (data_copy):\n", data_copy)


Original Array (data):
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
Modified Copy (data_copy):
 [99  8  6  8  7  9]


In [27]:
#Question 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

# Step 1: Create two matrices of identical shape
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Step 2: Perform addition
addition_result = A + B

# Step 3: Perform subtraction
subtraction_result = A - B

# Print the results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition Result (A + B):\n", addition_result)
print("Subtraction Result (A - B):\n", subtraction_result)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Addition Result (A + B):
 [[ 8 10 12]
 [14 16 18]]
Subtraction Result (A - B):
 [[-6 -6 -6]
 [-6 -6 -6]]


In [28]:
#Question 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

# Step 1: Generate two matrices
C = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3, 2)
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])  # Shape (2, 4)

# Step 2: Perform matrix multiplication
result = np.dot(C, D)
# Alternatively, I can use:
# result = C @ D

# Print the result
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix Multiplication Result (C @ D):\n", result)


Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]
Matrix Multiplication Result (C @ D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [29]:
#Question 83. Create a matrix `E` and find its transpose. 
import numpy as np

# Step 1: Create a matrix E
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Step 2: Find the transpose of E
E_transpose = E.T
# Alternatively, I can use:
# E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:\n", E)
print("Transpose of Matrix E:\n", E_transpose)


Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
#Question84. Generate a square matrix `F` and compute its determinant. 
import numpy as np

# Step 1: Generate a square matrix F
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Step 2: Compute the determinant of F
determinant = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F:\n", F)
print("Determinant of Matrix F:\n", determinant)
 

Matrix F:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Matrix F:
 -9.51619735392994e-16


In [31]:
#Question 85. Create a square matrix `G` and find its inverse. 

import numpy as np

# Step 1: Creating a square matrix G
G = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Step 2: Find the inverse of G
# Check if the matrix is singular (determinant is not zero) before computing the inverse
determinant = np.linalg.det(G)
if determinant != 0:
    G_inverse = np.linalg.inv(G)
    print("Matrix G:\n", G)
    print("Inverse of Matrix G:\n", G_inverse)
else:
    print("The matrix G is singular and does not have an inverse.")


Matrix G:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of Matrix G:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
